// by arrival
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

// by sale
export const PRODUCT_LIST_BY_SALE_REQUEST = "PRODUCT_LIST_BY_SALE_REQUEST";
export const PRODUCT_LIST_BY_SALE_SUCCESS = "PRODUCT_LIST_BY_SALE_SUCCESS";
export const PRODUCT_LIST_BY_SALE_FAIL = "PRODUCT_LIST_BY_SALE_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";
