export const WISHLIST_ADD_ITEM_FAIL = "WISHLIST_ADD_ITEM_FAIL";
export const WISHLIST_ADD_ITEM_SUCCESS = "WISHLIST_ADD_ITEM_SUCCESS";
export const WISHLIST_ADD_ITEM_REQUEST = "WISHLIST_ADD_ITEM_REQUEST";

export const WISHLIST_GET_REQUEST = "WISHLIST_GET_REQUEST";
export const WISHLIST_GET_SUCCESS = "WISHLIST_GET_SUCCESS";
export const WISHLIST_GET_FAIL = "WISHLIST_GET_FAIL";
